version: "3"
services: 
  spark-nlp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./notebooks:/app/notebooks
    expose:
      - 8888
    ports:
      - 8888:8888
    command: ["poetry", "run", "jupyter", "notebook",  "--debug", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
  neo4j:
    image: neo4j:4.3-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_unmanagedExtensionClasses=semantics.extension=/rdf
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science","n10s"]
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_dbms_memory_heap_initial__size:-4600m}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_dbms_memory_heap_max__size:-4600m}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_dbms_memory_pagecache_size:-1g}