version: "3"
services: 
  spark-nlp:
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - 8888
    ports:
      - 8888:8888
    command: ["poetry", "run", "jupyter", "notebook",  "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
